# Este archivo de workflow se utiliza para construir y desplegar una aplicación Node.js en Azure Web App
# Docs para la acción de Deploy en Azure Web Apps: https://github.com/Azure/webapps-deploy
# Más acciones para Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mi-aplicacion-web

# Triggers para que este workflow se ejecute
on:
  push:
    branches:
      - main   # Ejecutar cuando hay push a la rama 'main'
  workflow_dispatch: # Permitir ejecución manual del workflow

jobs:
  build-and-deploy:   # Nombre del trabajo
    runs-on: ubuntu-latest   # Utilizará un contenedor Ubuntu

    steps:
      - name: 'Checkout GitHub Action'   # Obtiene el código del repositorio
        uses: actions/checkout@v3

      - name: Set up Node.js version     # Configura la versión de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'           # Versión de Node.js (puede ser 18.x si prefieres)

      - name: Install dependencies and build  # Instalar dependencias y construir la aplicación
        run: |
          npm install                    # Instalar dependencias
          npm run build --if-present     # Ejecutar el script build si está presente

      - name: 'Deploy to Azure Web App'  # Acción para desplegar en Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mi-aplicacion-web'  # Nombre de tu Azure Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Usa el secreto para el deploy
